# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ASHIT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FastScroll'
	pod 'RxSwift'
  #pod 'RxCocoa', '~> 5'

end


# RxTest and RxBlocking make the most sense in the context of unit/integration tests
#target 'YOUR_TESTING_TARGET' do
#    pod 'RxBlocking', '~> 5'
#    pod 'RxTest', '~> 5'
#end
